### PR TITLE
Update gacha_tables.py

### PR DESCRIPTION
**Pull request by Chesh-cat**
added only to loot list. added only to list of ratoon pulls (I think) Edited description of Stowaway cheshire (I will do this every time I update)

### CODE REVIEW

**Comment by hillexed** [comment]
Next time, a more descriptive commit message would be nice, like "Add Only to gacha"

**Comment by hillexed** [comment]
BodyPlanItems have an extra argument that is a dict with the data of the number of arms and legs in that body plan. Can you add them to the end of those two body plans? Look at other body plans for how it works. They do nothing now but maybe someday...

**Comment by Chesh-cat** [comment]
Can do.

**Comment by hillexed** [comment]
You have failed to do my bidding. A thousand years' dungeon while I must go do it myself.

**Comment by Chesh-cat** [comment]
I haven't touched this in a week or two?  I don't think I've put in any
descriptions that violated the style guide you laid down, as I haven't made
any pull requests.

**Pull request merged**
